//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApplication.StockService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StockService.IStockService")]
    public interface IStockService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/StockBuild", ReplyAction="http://tempuri.org/IStockService/StockBuildResponse")]
        string StockBuild(string URL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/StockBuild", ReplyAction="http://tempuri.org/IStockService/StockBuildResponse")]
        System.Threading.Tasks.Task<string> StockBuildAsync(string URL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/StockQuote", ReplyAction="http://tempuri.org/IStockService/StockQuoteResponse")]
        string StockQuote(string symbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStockService/StockQuote", ReplyAction="http://tempuri.org/IStockService/StockQuoteResponse")]
        System.Threading.Tasks.Task<string> StockQuoteAsync(string symbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStockServiceChannel : StockApplication.StockService.IStockService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockServiceClient : System.ServiceModel.ClientBase<StockApplication.StockService.IStockService>, StockApplication.StockService.IStockService {
        
        public StockServiceClient() {
        }
        
        public StockServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string StockBuild(string URL) {
            return base.Channel.StockBuild(URL);
        }
        
        public System.Threading.Tasks.Task<string> StockBuildAsync(string URL) {
            return base.Channel.StockBuildAsync(URL);
        }
        
        public string StockQuote(string symbol) {
            return base.Channel.StockQuote(symbol);
        }
        
        public System.Threading.Tasks.Task<string> StockQuoteAsync(string symbol) {
            return base.Channel.StockQuoteAsync(symbol);
        }
    }
}
