//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockApplication.ExchangeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/queryRate", ReplyAction="http://tempuri.org/IService/queryRateResponse")]
        double queryRate(string currencyFromSymbol, string currencyToSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/queryRate", ReplyAction="http://tempuri.org/IService/queryRateResponse")]
        System.Threading.Tasks.Task<double> queryRateAsync(string currencyFromSymbol, string currencyToSymbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : StockApplication.ExchangeService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<StockApplication.ExchangeService.IService>, StockApplication.ExchangeService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double queryRate(string currencyFromSymbol, string currencyToSymbol) {
            return base.Channel.queryRate(currencyFromSymbol, currencyToSymbol);
        }
        
        public System.Threading.Tasks.Task<double> queryRateAsync(string currencyFromSymbol, string currencyToSymbol) {
            return base.Channel.queryRateAsync(currencyFromSymbol, currencyToSymbol);
        }
    }
}
